***Лабораторная работа 1. Журавлев К. В. ПИ20-1***

**Задание 1**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import numpy.linalg as linalg

In [ ]:
x, y = np.mgrid[1:11, 1:11]
mat = x * y
mat

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

**Задание 2**

In [ ]:
def zadanie_2(el1, d, n):
    array = np.diag(np.arange(el1, el1 + d*n, d))
    return array
el1 = 1100
d = 100
n = 10
zadanie_2(el1, d, n)

array([[1100,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 1200,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0, 1300,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0, 1400,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0, 1500,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0, 1600,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0, 1700,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0, 1800,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0, 1900,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0, 2000]])

**Задание 3**

In [ ]:
data = np.genfromtxt('stockholm_td_adj.dat')

In [ ]:
a = data[(data[:,0]==1970) & (data[:,1]==10)]

In [ ]:
np.savetxt('temperature.txt', a, fmt='%.5f')
np.savetxt('temperature.bin', a, fmt='%.5f')

In [ ]:
temp = np.genfromtxt('temperature.txt')
temp

array([[1.97e+03, 1.00e+01, 1.00e+00, 1.07e+01, 1.04e+01, 1.04e+01,
        1.00e+00],
       [1.97e+03, 1.00e+01, 2.00e+00, 9.30e+00, 9.00e+00, 9.00e+00,
        1.00e+00],
       [1.97e+03, 1.00e+01, 3.00e+00, 8.10e+00, 7.80e+00, 7.80e+00,
        1.00e+00],
       [1.97e+03, 1.00e+01, 4.00e+00, 6.90e+00, 6.60e+00, 6.60e+00,
        1.00e+00],
       [1.97e+03, 1.00e+01, 5.00e+00, 8.20e+00, 7.90e+00, 7.90e+00,
        1.00e+00],
       [1.97e+03, 1.00e+01, 6.00e+00, 1.10e+01, 1.07e+01, 1.07e+01,
        1.00e+00],
       [1.97e+03, 1.00e+01, 7.00e+00, 1.25e+01, 1.22e+01, 1.22e+01,
        1.00e+00],
       [1.97e+03, 1.00e+01, 8.00e+00, 1.25e+01, 1.22e+01, 1.22e+01,
        1.00e+00],
       [1.97e+03, 1.00e+01, 9.00e+00, 1.05e+01, 1.02e+01, 1.02e+01,
        1.00e+00],
       [1.97e+03, 1.00e+01, 1.00e+01, 1.11e+01, 1.09e+01, 1.09e+01,
        1.00e+00],
       [1.97e+03, 1.00e+01, 1.10e+01, 9.90e+00, 9.70e+00, 9.70e+00,
        1.00e+00],
       [1.97e+03, 1.00e+01, 1.20e+01, 9.20e

In [ ]:
bin = np.genfromtxt('temperature.bin')
bin

array([[1.97e+03, 1.00e+01, 1.00e+00, 1.07e+01, 1.04e+01, 1.04e+01,
        1.00e+00],
       [1.97e+03, 1.00e+01, 2.00e+00, 9.30e+00, 9.00e+00, 9.00e+00,
        1.00e+00],
       [1.97e+03, 1.00e+01, 3.00e+00, 8.10e+00, 7.80e+00, 7.80e+00,
        1.00e+00],
       [1.97e+03, 1.00e+01, 4.00e+00, 6.90e+00, 6.60e+00, 6.60e+00,
        1.00e+00],
       [1.97e+03, 1.00e+01, 5.00e+00, 8.20e+00, 7.90e+00, 7.90e+00,
        1.00e+00],
       [1.97e+03, 1.00e+01, 6.00e+00, 1.10e+01, 1.07e+01, 1.07e+01,
        1.00e+00],
       [1.97e+03, 1.00e+01, 7.00e+00, 1.25e+01, 1.22e+01, 1.22e+01,
        1.00e+00],
       [1.97e+03, 1.00e+01, 8.00e+00, 1.25e+01, 1.22e+01, 1.22e+01,
        1.00e+00],
       [1.97e+03, 1.00e+01, 9.00e+00, 1.05e+01, 1.02e+01, 1.02e+01,
        1.00e+00],
       [1.97e+03, 1.00e+01, 1.00e+01, 1.11e+01, 1.09e+01, 1.09e+01,
        1.00e+00],
       [1.97e+03, 1.00e+01, 1.10e+01, 9.90e+00, 9.70e+00, 9.70e+00,
        1.00e+00],
       [1.97e+03, 1.00e+01, 1.20e+01, 9.20e

**Задание 4**

In [ ]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
A[::, 1::2]

array([[ 1,  3],
       [11, 13],
       [21, 23],
       [31, 33],
       [41, 43]])

**Задание 5**

In [ ]:
mask = mat % 3 == 0
mat[mask]

array([ 3,  6,  9,  6, 12, 18,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 12,
       24, 36, 15, 30, 45,  6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 21, 42,
       63, 24, 48, 72,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 30, 60, 90])

**Задание 7**

In [ ]:
even = mat % 2 == 0 #Маски для отбора из таблицы умножения четных и нечетных элементов
odd = mat % 2 == 1

In [ ]:
even_array = mat[even] #Массив с четными числами
mat[even]

array([  2,   4,   6,   8,  10,   2,   4,   6,   8,  10,  12,  14,  16,
        18,  20,   6,  12,  18,  24,  30,   4,   8,  12,  16,  20,  24,
        28,  32,  36,  40,  10,  20,  30,  40,  50,   6,  12,  18,  24,
        30,  36,  42,  48,  54,  60,  14,  28,  42,  56,  70,   8,  16,
        24,  32,  40,  48,  56,  64,  72,  80,  18,  36,  54,  72,  90,
        10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
odd_array = mat[odd] #Массив с нечетными числами
mat[odd]

array([ 1,  3,  5,  7,  9,  3,  9, 15, 21, 27,  5, 15, 25, 35, 45,  7, 21,
       35, 49, 63,  9, 27, 45, 63, 81])

In [ ]:
#Первый способ
which = [] #В цикле создается массив единиц и нулей, чтобы функция choose понимала из какого массива в какой момент брать элементы
for i in range(len(mat)):
  for j in range(len(mat)):
    if mat[i,j] % 2 == 0:
      which.append(0)
    else:
      which.append(1)
choices = [[0, 2, 0,  4, 0, 6, 0, 8, 0, 10,   2,   4,   6,   8,  10,  12,  14,  16, # Массивы четных и нечетных чисел из таблицы умножения
        18,  20, 0, 6, 0, 12, 0, 18, 0, 24, 0, 30,   4,   8,  12,  16,  20,  24,    # Нули подставлены, потому что функция choose пропускает 
        28,  32,  36,  40, 0, 10, 0, 20, 0, 30, 0, 40, 0, 50,   6,  12,  18,  24,   # индекс после каждой вставки
        30,  36,  42,  48,  54,  60, 0, 14, 0, 28, 0, 42, 0, 56, 0, 70,   8,  16,
        24,  32,  40,  48,  56,  64,  72,  80, 0, 18, 0, 36, 0, 54, 0, 72, 0, 90,
        10,  20,  30,  40,  50,  60,  70,  80,  90, 100], [1, 0, 3, 0, 5, 0, 7, 0, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 9, 0, 15, 0, 21, 0, 27, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 15, 0, 25, 0, 35, 0, 45, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 21, 0, 35, 0, 49, 0, 63, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 0, 27, 0, 45, 0, 63, 0, 81, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]
np.choose(which, choices).reshape(10, 10)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [ ]:
#Второй способ
even = np.where(mat % 2 == 0, mat, 0)
even

array([[  0,   2,   0,   4,   0,   6,   0,   8,   0,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  0,   6,   0,  12,   0,  18,   0,  24,   0,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  0,  10,   0,  20,   0,  30,   0,  40,   0,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  0,  14,   0,  28,   0,  42,   0,  56,   0,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  0,  18,   0,  36,   0,  54,   0,  72,   0,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [ ]:
odd = np.where(mat % 2 != 0, mat, 0)
odd

array([[ 1,  0,  3,  0,  5,  0,  7,  0,  9,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 3,  0,  9,  0, 15,  0, 21,  0, 27,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 5,  0, 15,  0, 25,  0, 35,  0, 45,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 7,  0, 21,  0, 35,  0, 49,  0, 63,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 9,  0, 27,  0, 45,  0, 63,  0, 81,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [ ]:
np.choose(mat % 2 == 0, [odd, even])

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

**Задание 8**

In [ ]:
v1 = np.array([0,1,2,3,4])
v2 = np.array([5,6,7,8,9])
cosin = np.dot(v1,v2)/linalg.norm(v1)/linalg.norm(v2)
angle = np.arccos(np.clip(cosin, -1, 1)) * 57.3
print(angle)

23.844392305568718


**Задание 9**

In [ ]:
A = np.array([i for i in range(1, 26)]).reshape(5, 5) #Задаю матрицу 5х5 от 1 до 25
mask_odd = A % 2 != 0 #маски четных/нечетных чисел
mask_even = A % 2 == 0
A[mask_odd] = 5 #замена четных на 5, нечетных на 0
A[mask_even] = 0

In [ ]:
B = np.array([[-i + j for i in range(1, 6)] for j in range(5)]) #Задаю матрицу 5х5 таким образом, чтобы по основной диагонали и выше ее
mask_over = B <= -1                                             #стояли отрицательные числа
mask_under = B > -1 #маски для замены - меньше или равно -1 на 5, больше -1 на 0
B[mask_under] = 0
B[mask_over] = 5

In [ ]:
print(A, linalg.det(A)) #Матрица A и ее детерминант

[[5 0 5 0 5]
 [0 5 0 5 0]
 [5 0 5 0 5]
 [0 5 0 5 0]
 [5 0 5 0 5]] 0.0


In [ ]:
print(B, linalg.det(B)) #Матрица B и ее детерминант

[[5 5 5 5 5]
 [0 5 5 5 5]
 [0 0 5 5 5]
 [0 0 0 5 5]
 [0 0 0 0 5]] 3124.999999999999


In [ ]:
B_inv = linalg.inv(B) #Обратная матрица B (обратная матрица A не строится из-за нулевого детерминанта)
B_inv

array([[ 0.2, -0.2,  0. ,  0. ,  0. ],
       [ 0. ,  0.2, -0.2,  0. ,  0. ],
       [ 0. ,  0. ,  0.2, -0.2,  0. ],
       [ 0. ,  0. ,  0. ,  0.2, -0.2],
       [ 0. ,  0. ,  0. ,  0. ,  0.2]])