Журавлев К. В. ПИ20-1 Лабораторная 2 ТОБД

Задание 1

In [ ]:
import numpy as np
[np.arange(1,8,1) + np.arange(0, 110, 10).reshape(11, 1)]

[array([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])]

Задание 2


In [ ]:
a = np.arange(1,21,1)[1::2]
b = np.arange(1,22,1)[2::2]
a*b

array([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

Задание 3


In [ ]:
x = np.arange(0, 11, 1)
t3 = x * np.sin(x)
m = (0.5 < t3)
m
print(x[m])

[1 2 7 8 9]


Задание 4

In [ ]:
a = np.random.randint(0, 11, (3, 3))
b = np.argmin(np.sum(a, axis = 1))
print(a, a[b], b)

[[ 2  5  9]
 [ 5  7  1]
 [10  4  0]] [5 7 1] 1


Задание 5

In [ ]:
a = np.random.randint(0, 10, (3, 3))
a = np.random.randint(0, 10, (3, 3))
res = sum(a[a > b])
print(a, b, res, sep='\n')

[[1 4 1]
 [7 4 3]
 [7 1 3]]
1
28


Задание 6

In [ ]:
def func1(m, n):
  arr = np.zeros((n, m))
  arr[1::2] = arr[1::2] + 2
  arr[:, 1::2] = arr[:, 1::2] + 1
  return arr
func1(4, 4)

array([[0., 1., 0., 1.],
       [2., 3., 2., 3.],
       [0., 1., 0., 1.],
       [2., 3., 2., 3.]])

Задание 7


In [ ]:
def func2(n=100):
  k = n
  o = np.arange(1, k + 1, 1)
  s = o.reshape(k, 1)
  f = o.reshape(1, k)
  o = o[(f % s == 0).sum(axis = 0) == 2]
  return o
func2(100)

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])

Задание 8

In [ ]:
arr = np.array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'])
call = np.array(np.random.randint(0, 10, 100))
arr[call]

array(['D', 'H', 'C', 'D', 'E', 'B', 'C', 'B', 'I', 'G', 'C', 'E', 'B',
       'J', 'H', 'I', 'C', 'J', 'J', 'G', 'J', 'B', 'G', 'G', 'F', 'F',
       'G', 'E', 'C', 'D', 'E', 'H', 'J', 'E', 'H', 'C', 'F', 'J', 'F',
       'I', 'G', 'A', 'A', 'C', 'I', 'F', 'H', 'J', 'F', 'F', 'C', 'J',
       'I', 'J', 'B', 'J', 'G', 'A', 'I', 'E', 'A', 'H', 'H', 'J', 'G',
       'A', 'E', 'C', 'I', 'B', 'F', 'I', 'H', 'C', 'B', 'D', 'C', 'H',
       'D', 'D', 'E', 'F', 'C', 'A', 'H', 'C', 'C', 'C', 'G', 'J', 'J',
       'B', 'E', 'F', 'I', 'B', 'F', 'I', 'H', 'H'], dtype='<U1')

Задание 9

In [ ]:
l9=np.random.randint(0,11,size=(20,20), dtype=int)
print(l9)
row_id=np.arange(0, 19, 1)
col_id=row_id+1
l9[row_id, col_id]

[[ 5  4 10  4  7  5  5  3  7  9  3  1  3  7  9  8  5  9  1  4]
 [ 6  7  3  5  0  6  0  4  6  1  1  1  6  8  6  1  9  3  0  8]
 [ 8  7  2  9  4  4  9  9  4  9  1  9  8  8  0  2  9  1  7 10]
 [ 7  6  1  7  7  5  4  5 10  8  0  0  3  0  7 10 10  4  5  7]
 [ 5  3  9  9  3  2  1  3  3  0  5 10  5  0  6  5  4  7  0 10]
 [ 2  2  2  9  9 10  4  6  7  8  7  7  4  6  1  6  0  6  4  9]
 [ 3  2  9  9  9  6  1  3  2  2  7  8  7  1  2  9  4  2  0  6]
 [ 9  2  2  5  9  4  5  7  1  9  8  0  8  3  4  4 10  2  5  1]
 [ 9  3  4  7  5  6  3  7  7  7  6  3  3  3  1  2  8  3  6  5]
 [ 3  5  2  1  1 10  1  0  2 10  1  0  2  8  5 10  9  8  6  0]
 [ 3  6 10  9  2  6 10  5  2  8  5  6  6  8  2  7  0  1  4  1]
 [10  2  3  6  9  9  8  3  8  1  1 10  4  6  6  3  1  0  4 10]
 [ 0  8  4  2  5  9  0  5  7  0 10  0  0  8  8  8  5  8  2 10]
 [10  5  6  3  9  9  0  8  9  1  9  2  1  3  2 10  1  1  7  5]
 [ 6  7  4  8  1  4  0  1  6  2  9  1  8  8  2  9  0  0  7  2]
 [ 9  8  3  7  8  9  4  4 10  1  1  8  9  7  1  1 10  8

array([ 4,  3,  9,  7,  2,  4,  3,  1,  7,  1,  6,  4,  8,  2,  9, 10,  7,
        0,  3])