# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [ ]:
import numpy as np
arr = np.random.rand(4,7)*20
print(arr)
arr_new = arr/(arr.max() - arr.min()) + arr.min()/(arr.min()-arr.max())
print(arr_new)

[[ 1.43717062  6.27558754 16.12582206  5.94017818 19.52224797 16.00190487
   5.59774558]
 [18.9558319  12.42294679 18.53248047  7.23023637 18.75199364 11.08452292
   8.13004062]
 [ 2.58017671 12.77518257 14.07182646  5.62830155 17.15946423  4.45312715
   6.98196699]
 [ 1.99433898 10.97046395 18.78651845 16.53648767 14.15917113  2.75549492
  13.22970765]]
[[0.         0.26753642 0.81219732 0.24899023 1.         0.80534542
  0.23005569]
 [0.96868047 0.60744977 0.94527159 0.32032297 0.9574094  0.53344269
  0.37007694]
 [0.06320161 0.62692637 0.69862327 0.23174526 0.86935175 0.16676492
  0.30659512]
 [0.03080818 0.52713589 0.95931842 0.83490475 0.70345292 0.0728957
  0.65205898]]


2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [ ]:
arr = np.random.randint(0,11,(8,10))
print(arr)
print(f'Строка ={arr[np.argmin(np.sum(arr, axis=1))]}, Индекс={np.argmin(np.sum(arr, axis=1))}')

[[ 5  0  0  9  6  8  9 10  4  5]
 [10  0  9  8  5  6  9 10  0  7]
 [ 7  6  5  7  5  0  6  9  3  5]
 [ 9 10  0  0  8  0 10  6  7  0]
 [ 3  4  9  2  3  2  9  8  5  8]
 [ 2 10  8  3  8  3  2  1  2 10]
 [ 2  3  1  3  0  3  9  8  2  7]
 [ 1  0  3  9  9  7  9  0  9  9]]
Строка =[2 3 1 3 0 3 9 8 2 7], Индекс=6


In [ ]:
arr = np.random.randint(0,11,(8,10))
print(arr)
print(f'Строка ={arr[:,np.argmin(np.sum(arr, axis=0))]}, Индекс={np.argmin(np.sum(arr, axis=0))}')

[[ 2  6  0  1  4  9  7  1  2  8]
 [10  5  7  1 10  9  9 10  5  3]
 [ 4  4  0  2  8  8  8  8  4  6]
 [ 3  1  1  0  4  2 10  8  3  9]
 [ 8  2  4 10  4  6  0  0  3 10]
 [ 2  9  5  9 10  8  1  8  7  0]
 [ 7  1  3  4  2 10  6  8  6 10]
 [ 2  3  5  1  7  3  5  1  1  4]]
Строка =[0 7 0 1 4 5 3 5], Индекс=2


3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [ ]:
a = np.array([0,4])
b = np.array([3, 0])
np.sqrt(((b - a)**2).sum())
np.linalg.norm(b-a)

5.0

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [ ]:
A = np.array([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = np.array([[3, -1], [2, 1]])
C = np.array([[7, 21], [11, 8], [8, 4]])
#A^-1*A*X*B*B^-1 = A^-1 * (-C) * B^-1
X = np.linalg.inv(A) @ (-C) @ np.linalg.inv(B)
X

array([[ 1.00000000e+00,  5.32907052e-16],
       [-2.00000000e+00,  1.00000000e+00],
       [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

In [ ]:
m_n_i = np.loadtxt('minutes_n_ingredients.csv', dtype='int32', skiprows=1, delimiter=',') #max_rows=5
un = np.unique(m_n_i[:,(1,2)], axis=0)
un.size

8390

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [ ]:
ds = np.loadtxt('minutes_n_ingredients.csv', dtype=int, delimiter=",", skiprows=1)
print(ds[:5])

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       ...,
       [498432,     65,     15],
       [370915,      5,      4],
       [ 81993,    140,     14]], dtype=int32)

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [ ]:
print(np.min(ds[:, 1]), np.max(ds[:, 1]), np.median(ds[:, 1]), np.mean(ds[:, 1]))
print(np.min(ds[:, 2]), np.max(ds[:, 2]), np.median(ds[:, 2]), np.mean(ds[:, 2]))

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [ ]:
data2 = ds.copy()
limit = np.quantile(data2[:,1:2], 0.75)
data2 = data2[data2[:,1] <= limit]
data2.shape

65.0


(75461, 3)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [ ]:
data1 = ds.copy()
count = data1.shape[0] - np.count_nonzero(data1[:,1])
print(count)
np.place(data1[:,1], data1[:,1]==0, 1)

0


1

5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [ ]:
un = np.unique(ds[:, (1,  2)], axis = 0)
un.size

2250

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [ ]:
ingr = ds.copy()
ingr = ingr[:,2]
print(np.unique(ingr), len(np.unique(ingr)))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 33 34]


32

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [ ]:
mask = ds[:, 2] <= 5
print(ds.shape, ds[mask].shape)

(14890, 3)

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [ ]:
mask = ds[:, 1] != 0
ds2 = ds[mask]
average = ds2[:, 2] / ds2[:, 1]
np.max(average)

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [ ]:
ds[ds[:, 1].argsort()[::-1]][:100,2].mean()

10.06

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [ ]:
m_n_i[np.random.randint(m_n_i.shape[0],size=10),:]

array([[270154,     25,      5],
       [393143,     45,     17],
       [502609,     20,     10],
       [ 23315,     20,      8],
       [ 97116,     32,      6],
       [100949,      1,      4],
       [ 80999,     40,      4],
       [187748,     45,     11],
       [243343,     30,     11],
       [329230,      2,      4]], dtype=int32)

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [ ]:
mask = ds[:,2]<np.mean(ds[:,2])
print(100*len(ds[mask]/len(ds)))

52.51056837306688


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [ ]:
is_simple_mask = (ds[:, 1] < 21) & (ds[:, 2] < 6)
new_ds = np.c_[ds, is_simple_mask]
new_ds

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,    140,     14,      0]], dtype=int32)

13. Выведите процент "простых" рецептов в датасете

In [ ]:
mask = new_ds[:, 3] == 1
new_ds[mask].shape[0] * 100 / new_ds.shape[0]

9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [ ]:
short = new_ds[new_ds[:,1]<10]
standart = new_ds[(new_ds[:,1]>=10) & (new_ds[:,1]<20)]
long = new_ds[20<=new_ds[:,1]]
max_ = np.min([short.shape[0], standart.shape[0], long.shape[0]])
np.array([short[:max_], standart[:max_], long[:max_]])

(3, 7588, 4)